### PR TITLE
Minor bug fixes found with static analysis checks with cppcheck

### PR DESCRIPTION
**Pull request by ColinIanKing**
Just a few minor bugs found, can these be merged?

### CODE REVIEW

**Comment by tkanteck** [comment]
@ColinIanKing many thanks for making the fixes. Unfortunately, I cannot just merge your pull request due to our SCM infrastructure setup. However all your commits from the pull request have been pushed to master.
We have also added cppcheck target to all makefiles for convienience of re-runing it as code changes.
Is it OK to close your pull request?

**Comment by ColinIanKing** [comment]
On 13/10/15 16:45, Tomasz Kantecki wrote:
> @ColinIanKing <https://github.com/ColinIanKing> many thanks for making
> the fixes. Unfortunately, I cannot just merge your pull request due to
> our SCM infrastructure setup. However all your commits from the pull
> request have been pushed to master.

Ack, thanks!

> We have also added cppcheck target to all makefiles for convienience of
> re-runing it as code changes.
> Is it OK to close your pull request?

Yep.

I'm looking at packaging this up for Debian/Ubuntu if that's OK

Colin

**Comment by tkanteck** [comment]
> 
> I'm looking at packaging this up for Debian/Ubuntu if that's OK
>

This is perfect! What is your schedule?
We could run full validation cycle on this code & tag new release, if enough time.

Thanks
Tomasz 

--------------------------------------------------------------
Intel Shannon Limited
Registered in Ireland
Registered Office: Collinstown Industrial Park, Leixlip, County Kildare
Registered Number: 308263
Business address: Dromore House, East Park, Shannon, Co. Clare

This e-mail and any attachments may contain confidential material for the sole use of the intended recipient(s). Any review or distribution by others is strictly prohibited. If you are not the intended recipient, please contact the sender and delete all copies.

**Comment by ColinIanKing** [comment]
On 13/10/15 20:42, Tomasz Kantecki wrote:
>>
>> I'm looking at packaging this up for Debian/Ubuntu if that's OK
>>
> 
> This is perfect! What is your schedule?

We have a 15.10 release coming up soon but it is too late to land code
in that now. After October I can do some initial packaging, but I can
keep on re-syncing with the latest tagged release until about feb/mar
2016 for the Ubuntu 16.04 LTS.

Colin

**Comment by tkanteck** [comment]
Sounds great! Let's keep in touch.

**Comment by ColinIanKing** [comment]
On 16/10/15 13:17, Tomasz Kantecki wrote:
> Sounds great! Let's keep in touch.

I've got some more open issues that I'll fix up that were found with
Coverity, so I'll try and address this in the next week or so.

Colin

**Pull request closed without merging**
